# Generated by Django 3.2.3 on 2021-05-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
